# Site settings
title: The Drone Short Film Site
email: petrovs.maris@gmail.com
description: > # A short film depicting a near future where we have become a society entirely under surveillance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thedronefilm.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  puzurs

# Build settings
markdown: kramdown
